### ISSUE TITLE
New version not powering up via battery

### ISSUE THREAD

**Issue by russrussw** [Xinyuan-LilyGO/T-A7670X#14]
I have the latest board version V1.1 of date 2022-5-22 which will NOT power up using the battery switch. I have 30 of these boards :-( Battery fully charged at 4.12v however boards seems to work using usb. Although some issue with modem turning on then off again.

**Comment by LilyGO** [comment]
Hello, which sketch are you running? Try this [sketch ](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/examples/new_version/Arduino/TinyGSM_Net_GNSS/TinyGSM_Net_GNSS.ino)to see if it works

**Comment by russrussw** [comment]
Thanks test solved it 👍🏻

**Comment by rustyw** [comment]
I discovered this board does no longer have a LED you can program unlike previous versions. So when powering up via battery no lights go on at all, making it seem as though it is OFF. Unless you plug a solar cell on the solar input.

**Comment by LilyGO** [comment]
> I discovered this board does no longer have a LED you can program unlike previous versions. So when powering up via battery no lights go on at all, making it seem as though it is OFF. Unless you plug a solar cell on the solar input.

Hello, Please refer to the sketch. To use batteries, you need to enable IO12 (see schematic diagram).
