### ISSUE TITLE
SD card not functioning

### ISSUE THREAD

**Issue by rustyw** [Xinyuan-LilyGO/T-A7670X#16]
Using the supplied firmware that came with the board and trying different SD cards using FAT, FAT32 I am not able to get it to work.
Even when trying SD firmware that works well on the LilyGo SIM7000G I get the same results on this board. I have double checked the CS, MISO, MOSI and CLK wires but to no avail. There are definitely issues with these boards.

**Comment by LilyGO** [comment]
Hello. These boards are tested with SD cards in factory testing. Did you buy a T-A7670 or a T-SIM7000? Sometimes it's a bug in the esp32 package. What is your current esp32 version? It should have been fixed in the latest package, please refer to the changelog of the esp32 package!

**Comment by rustyw** [comment]
He

Here are the images of the new board.

![IMG_6188](https://user-images.githubusercontent.com/8700185/181445704-5bde7ae3-ac4f-45d6-a408-2251cb4cf9de.jpg)
![IMG_6186](https://user-images.githubusercontent.com/8700185/181445763-797ebfe0-90f2-4ca3-b4ef-f543d4509ae2.jpg)

Thank you.

**Comment by LilyGO** [comment]
Running this [sketch](https://github.com/Xinyuan-LilyGO/T-A7670X/tree/main/examples/new_version/Arduino/TinyGSM_Net_GNSS) can detect TF cards?
