### ISSUE TITLE
Deep sleep mode

### ISSUE THREAD

**Issue by BJ4K3** [Xinyuan-LilyGO/T-A7670X#18]
Hi, I would like to put the board in deep sleep, I've tried turning off the modem with the `AT+CPOF` AT command (naturally I've set the esp32 in hibernation mode) but the total consumption is around 66mA and not the 0.18mA you indicated. Can I have some sort of code to put the entire board in sleep mode reaching the current consumption you mentioned?

Thank you.

**Comment by LilyGO** [comment]
Reference [sketch](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/examples/new_version/Arduino/TinyGSM_Net_GNSS/TinyGSM_Net_GNSS.ino). sleep at the end.

**Comment by BJ4K3** [comment]
Hi, as said I have already tried the AT+CPOF command (like the tinygsm library) but the board absorb too much current even after the command and the ESP32 in hibernate mode.

**Comment by LilyGO** [comment]
Did you run the sketch above?

**Comment by LilyGO** [comment]
No reply for a long time. Close
