### ISSUE TITLE
measured battery voltage does not change

### ISSUE THREAD

**Issue by nukutoki** [Xinyuan-LilyGO/T-A7670X#19]
Hi,
I am using the battery voltage [example](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/examples/new_version/Arduino/battery_voltage/battery_voltage.ino).
The measured battery voltage is always 4.04V (if no USB is connected). I am using [this](https://pt.aliexpress.com/item/1005003036514769.html) board. Should the example work on this board or do I have to connect the GPIO35 somehow?
Thanks in advance.

**Comment by LilyGO** [comment]
Hello.The battery check function is available only for 2022-7-28 V1.2.

**Comment by nukutoki** [comment]
OK, thank you for the fast reply.

**Comment by giannoug** [comment]
@LilyGO So how can we check battery voltage for 2022-5-22 V1.1?

**Comment by LilyGO** [comment]
Hello. Only V1.2 has the function of detecting battery voltage

**Comment by giannoug** [comment]
Which pin of the board has battery voltage? VBAT? We could be able to use a voltage divider to calculate it

**Comment by LilyGO** [comment]
V1.2.    The IO35 can capture battery voltage

**Comment by LilyGO** [comment]
I'm sorry. V1.1 does not have a GPIO for ADC to detect battery voltage
