### ISSUE TITLE
GPS Example

### ISSUE THREAD

**Issue by fcojaviergl** [Xinyuan-LilyGO/T-A7670X#20]
Hi, 

I am new with Arduino, I have the board A7670 v1.2, and I would like to test the GPS, but I can't use internet examples, can you upload a GPS example in the repo?

Thanks.

**Comment by LilyGO** [comment]
Hello. You can use this [example](https://github.com/Xinyuan-LilyGO/T-A7670X/tree/main/examples/new_version/Arduino/TinyGSM_Net_GNSS)

**Comment by fcojaviergl** [comment]
Thanks, I didn't see it.

**Comment by walidbouachour** [comment]
hi , so i have a error in this example ,can you help me ?






gps:285:5: error: 'SerialMon' was not declared in this scope

     SerialMon.print("\tWait GPS reday.");

     ^

Plusieurs bibliothèque trouvées pour "SD.h"



exit status 1

'SerialMon' was not declared in this scope
