### ISSUE TITLE
SD Card IO Pins

### ISSUE THREAD

**Issue by daveymg-nz** [Xinyuan-LilyGO/T-A7670X#26]
If there is no SD card inserted, can the  SD card IO pins be used for other purposes?

**Comment by LilyGO** [comment]
The pin of the SD card is not extended

**Comment by daveymg-nz** [comment]
Thanks for your reply. I may not be understanding the pinout correctly, on the A7670SA pin diagram it shows GPIO 13, 14, 15 on the board edge pins, are these different to the 13, 14 and 15 listed as used by the SD card?

**Comment by LilyGO** [comment]
It can be used

**Comment by daveymg-nz** [comment]
Excellent,  thanks.
