### ISSUE TITLE
Device waken up from deep sleep after random time

### ISSUE THREAD

**Issue by mp-mba** [Xinyuan-LilyGO/T-A7670X#28]
Hi,

I'm testing the device as a controller for door sensor.
I would like to wake up the device from the deep sleep using `esp_sleep_enable_ext0_wakeup`.
But my problem is the the device is waken up immediately after going to sleep, without any state change on my pin.
I was eliminating line by line from `examples/new_version/platformio/src/main.cpp` code and I've tracked the piece of code that is causing this behaviour:

```
    pinMode(PWR_PIN, OUTPUT);
    digitalWrite(PWR_PIN, LOW);
    delay(100);
    digitalWrite(PWR_PIN, HIGH);
    delay(1000);
    digitalWrite(PWR_PIN, LOW);
```

Can you explain to me what is the purpose of those lines of code?
Is hard to me to understand it. Sorry for that, I'm still learning.
Thanks in advance.

**Comment by LilyGO** [comment]
Hello. This code starts A7670
