### ISSUE TITLE
How to update firmware?

### ISSUE THREAD

**Issue by bakup** [Xinyuan-LilyGO/T-A7670X#36]
There is an update instruction for LilyGo-T-Call-SIM800. Is it suitable for this board?
https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/master/doc/How%20to%20update%20firmware.md

**Comment by ycHawk** [comment]
Also I can **_not_** fully follow the instructions given in this documenation here
https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/docs/update_fw.md
