### ISSUE TITLE
Connecting device using SPI (i.e.LoRA)

### ISSUE THREAD

**Issue by ivicajan** [Xinyuan-LilyGO/T-A7670X#38]
Dear developers,
I would like to add a loRA shield to the T-A7670E and to do that I need standard sets of pins to connect to.
Overall, the project is aiming to collect the data using a loRA shield, store them on an SD card, use GPS location/time, and upload packages via SIM card modem to the server.
 
What would you suggest which pins could be used on the board that are not already taken? 
In particular, I would need something like this (but pins that I can use):
#define pin_ss 5
#define pin_rst 32
#define pin_dio0 34
#define pin_dio1 39
#define pin_mosi 23
#define pin_miso 19
#define pin_sck  18

Thanks in advance!

**Comment by lewisxhe** [comment]
IO33 and above can only be inputted, while IO33 and below can be inputted and outputted
