### ISSUE TITLE
Beeping sound - device freezes on battery

### ISSUE THREAD

**Issue by mykindofit** [Xinyuan-LilyGO/T-A7670X#40]
My code is using deep sleep and it was working fine for couple of weeks.
But now my device freezes when working on battery. 
Sometimes it wakes up, but more often it stuck in this state till I make restart (and/or plug external power).

During those freezes device is making some weird beeping sound.
There is a link to the video: https://drive.google.com/file/d/1E8bzVIb1ksJ1RlMGsdOGy981ow-VHJOF/view?usp=sharing
I hope it will be hearable when the make it a little bit louder.

**Comment by lewisxhe** [comment]
This problem is likely caused by a slight load causing DC inductance to scream, and there is currently no solution to this. This is a hardware issue
