### ISSUE TITLE
how to receive and send sms !

### ISSUE THREAD

**Issue by walidbouachour** [Xinyuan-LilyGO/T-A7670X#42]
it ther a code for that , can you help me ?

**Comment by lewisxhe** [comment]
here is the manual
https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/Manual/A76XX%20Series_AT_Command_Manual_V1.05.pdf

TinyGSM also has examples of sending text messages, they should be universal
https://github.com/vshymanskyy/TinyGSM/blob/8a911b218c1b2d03bb741855018fca062cefc479/examples/AllFunctions/AllFunctions.ino#L331

**Comment by lewisxhe** [comment]
If there are still issues, please reopen it
