### ISSUE TITLE
any help with starting with VSCODE?

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/T-A7670X#45]
Hi,

I have lots of ESP32 TTGO Lora Modules and want to test this TTGO LILYGO A7670SA now

as per intructions, there is no detail as to what type of board I should declare when importing the project on VSCO

any help?

**Comment by lewisxhe** [comment]
Just select esp32dev

```

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed =  961200
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder

```
