### ISSUE TITLE
A7670E PPS connected to ESP32?

### ISSUE THREAD

**Issue by morgana2313** [Xinyuan-LilyGO/T-A7670X#50]
The schematic of this board mentions pin 100 on the SIM7670 is a PPS signal. I could not find any information that the SIM7670 has a PPS output.

According to the file `GPSShield.ino: #define BOARD_GPS_PPS_PIN                   23` it's connected to ESP pin 23. Is that correct?
I'm looking for an ESP32 board with a GNSS + PPS.

**Comment by lewisxhe** [comment]
GPSShiled is an example of an external GPS module, not for internal use

A7670 does not connect 1PPS signal to ESP
