### ISSUE TITLE
Problem with GPS

### ISSUE THREAD

**Issue by jmpmscorp** [Xinyuan-LilyGO/T-A7670X#52]
Hi.

My company bougth one of those boards but I don't know if it was with or without GPS. I have been working with it without any problem using ESP-IDF modem component (pppos client, cmux,...).

Now, I want to use A7670G incorporated GNSS in a project. However, any command related with GPS answer with ERROR response. AT+CGNSSPWR, AT+CGPSINFO, AT+CAGPS,.. with everyone I get <ERROR> response. It makes me think that modem was bougth without GPS version. If those command would be supported, AT+CGNSSPWR=? response should be valid instead GPS was not correctly configured.

Check pictures of responses here: [https://community.lilygo.cc/topic/474/lilygo-t-a7670g-gps-problem](https://community.lilygo.cc/topic/474/lilygo-t-a7670g-gps-problem)

My question is... is it a "problem" with A7670G device that has not internally GPS device? or, is it problem with A7670G firmware version? If board bought was not GPS version, is there a way to enable GPS uploading new firmware version to modem?

Response to AT+SIMCOMATI:

Manufacturer: INCORPORATED
Model: A7670G-LLSE
Revision: A011B12A7670M7
A7670M7_B12V02_220613
QCN:
IMEI: 867284060415744
MEID:
+GCAP: +CGSM,+FCLASS,+DS
DeviceInfo:

OK

**Comment by lewisxhe** [comment]
a7670g no gps

**Comment by lewisxhe** [comment]
A7670G does not have GPS, different versions of firmware cannot be input
