### ISSUE TITLE
A7670E CGNSSMODE value for GPS and gallileo

### ISSUE THREAD

**Issue by harf18** [Xinyuan-LilyGO/T-A7670X#54]
Hi,

I bought the A7670E with  GPS
I red the datasheet [A76XX Series_AT_Command_Manual_V1.06.pdf](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/datasheet/A76XX%20Series_AT_Command_Manual_V1.06.pdf)
But I don't understand "The mode is supported by the ASR1603 projects and ASR1803S projects inforeign module:"

Can I use GPS AND GALILEO (at least) ? What is the correct CGNSSMODE code ?

Thanks

**Comment by lewisxhe** [comment]
SIMCOM replied that the default startup is `gps+glonass+gaileo`, the data sheet has been updated to [V1.09](https://github.com/Xinyuan-LilyGO/T-A7670X/blob/main/datasheet/A76XX_Series_AT_Command_Manual_V1.09.pdf), please check
