### ISSUE TITLE
How to update "GPSShiled_T-A7670X_20230613.bin" to T-A7670G ?

### ISSUE THREAD

**Issue by booroono** [Xinyuan-LilyGO/T-A7670X#56]
How to update "GPSShiled_T-A7670X_20230613.bin" to T-A7670G ?

**Comment by lewisxhe** [comment]
This firmware is for an external GPS module. Are you sure you have a GPS on your board?

**Comment by booroono** [comment]
I have the T-A7670G model. 
So, does the T-A7670E support GPS?
Please check.

**Comment by lewisxhe** [comment]
no support

**Comment by lewisxhe** [comment]
Check your order and send it to customer service for confirmation

**Comment by booroono** [comment]
I already left about this on "www.lilygo.cc"
What does external GPS module mean?
pls show me the image.
However, the 7670G and 7670E have a GPS antenna socket.

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-A7670X/assets/22990954/bf5739b4-3bd5-4fe6-a157-2c4770af7b04)

**Comment by booroono** [comment]
Thanks lewisxhe,
but 
<img width="585" alt="image" src="https://github.com/Xinyuan-LilyGO/T-A7670X/assets/96554546/00ea8bdd-1f75-4800-b09a-968c3603e85f">
I'll try to find another module.
thanks again.
