### ISSUE TITLE
T-A7670G GPS not working.

### ISSUE THREAD

**Issue by booroono** [Xinyuan-LilyGO/T-A7670X#57]
Hi all, 
I have two T-A7670Gs.
The HW version is V1.2 (2022-7-18).
![1](https://github.com/Xinyuan-LilyGO/T-A7670X/assets/96554546/2f681d2c-9e89-4fb3-bb8d-2ecaedf0e574)
I want to use real time GPS tracking.
But the GPS doesn't work.
<img width="567" alt="image" src="https://github.com/Xinyuan-LilyGO/T-A7670X/assets/96554546/819e51e4-deb9-4f9b-905e-48083bfe8f1c">
additional information as below.
---------------------------
AT+SIMCOMATI

Manufacturer: INCORPORATED
Model: A7670G-LLSE
Revision: A011B15A7670M7
A7670M7_B15V01_230111
---------------------------

**Comment by lewisxhe** [comment]
7670G  nosupport gps

**Comment by ShonkyCH** [comment]
> 7670G no support gps

You should fix your AliExpress listing then:

![image](https://github.com/Xinyuan-LilyGO/T-A7670X/assets/7312733/bbf80f23-002b-4dfa-858b-c79ab5f39cf6)

**Comment by lewisxhe** [comment]
Check your order and send it to customer service for confirmation
