### ISSUE TITLE
Pins avaible

### ISSUE THREAD

**Issue by metarsul** [Xinyuan-LilyGO/T-A7670X#62]
Hello I am new to this world of esp32.
I developed a program using a simple development board where I configured Serial1 to connect to an RS485 module using pins 16 and 17
I saw that many pins on this module are reserved and in many examples they use serial1 for AT commands. What pins can I use and can I declare serial1 in the code to use them?

**Comment by HDC67** [comment]
![pinout](https://raw.githubusercontent.com/Xinyuan-LilyGO/T-A7670X/main/image/new_version.jpg)

And check the schematic to see which pins have net labels that are used. Some of them like IO12 are used to enable power to the modem as well as being available on the module headers

**Comment by metarsul** [comment]
i was able to use pins 32 and 34
