### ISSUE TITLE
Can Lilygo T-A7670E charge internal battery from vbat pin?

### ISSUE THREAD

**Issue by CHaKUisMyName** [Xinyuan-LilyGO/T-A7670X#67]
hi

I have a question: Can Lilygo T-A7670E charge internal batter (NCR18650B) from external battery by vbat pin?

And can the battery be measured?

**Comment by theMladyPan** [comment]
battery is measured via resistor divider 100k:100k on GPIO35. Measure voltage on GPIO35 and multiply by 2.  VBAT pin is directly connected to battery, you can charge it via this pin using common li-ion chargers.

**Comment by CHaKUisMyName** [comment]
thank you @theMladyPan, it work for me
